{
    "name": "Cloudflare DDNS",
    "version": "1.0.0",
    "slug": "cloudflareddns",
    "description": "Update Cloudflare DDNS records.",
    "startup": "before",
    "boot": "auto",
    "docker": {
        "image": "oryx9760/cloudflareddns:v1.0.0",
        "privileged": false,
        "network_mode": "host"
    },
    "options": {
        "api_key": "",
        "zone_id": "",
        "record_id": "",
        "record_type": "A",
        "record_name": "",
        "update_interval": 3600
    },
    "schema": {
        "api_key": {
            "required": true,
            "type": "string",
            "description": "Cloudflare API key"
        },
        "zone_id": {
            "required": true,
            "type": "string",
            "description": "Cloudflare Zone ID"
        },
        "record_id": {
            "required": true,
            "type": "string",
            "description": "Cloudflare DNS Record ID"
        },
        "record_type": {
            "required": true,
            "type": "string",
            "description": "DNS record type (A or CNAME)",
            "options": ["A", "CNAME"]
        },
        "record_name": {
            "required": true,
            "type": "string",
            "description": "DNS record name"
        },
        "update_interval": {
            "required": true,
            "type": "integer",
            "description": "Update interval in seconds",
            "default": 3600
        }
    }
}
